#!/bin/bash
is_package_installed(){
	local pkg
	for pkg in "$@"; do
		pacman -Q ${pkg} &> /dev/null && return 0
	done
	return 1
	}
pkg_remove(){
	local pkgs pkg opts
	for pkg in "$@"; do
		case ${pkg} in
			-*) opts+=(${pkg});;
			*) is_package_installed $pkg && pkgs+=(${pkg});;
		esac
	done
	pacman -Rdd ${opts[@]} ${pkgs[@]}
	}
remove_systemd(){
	local u
	pkg_remove --nosave --noconfirm systemd libsystemd systemd-sysvcompat lib32-systemd
	for u in \
		systemd-journal \
		systemd-journal-gateway \
		systemd-timesync \
		systemd-network \
		systemd-bus-proxy \
		systemd-journal-remote \
		systemd-journal-upload \
		systemd-resolve \
		; do
		id -u $u 2>/dev/null && userdel $u
		id -g $u 2>/dev/null && groupdel $u
	done
	}
ensure_system_user(){
	local user="$1" id="$2" comment="$3"
	if ! id -g "$user" 2>/dev/null; then
		groupadd -g "$id" log
	fi
	if ! id -u "$user" 2>/dev/null; then
		useradd -M -g "$user" -l -s /usr/bin/nologin -c "${comment}" -r -u "$id" "$user"
	fi
	}
setup_socklog(){
	ensure_system_user nobody 99 'powerless user'
	ensure_system_user log 19 'socklog user'
	rm -rf /var/service/socklog*
	rm -rf /etc/sv/socklog*
	rm -rf /var/log/socklog*
	rm -rf /var/log/kernel
	for x in unix klog; do 
		[ ! -d "/etc/sv/socklog-$x" ] && socklog-conf $x nobody log
		ln -s ../../../sv/socklog-$x /etc/runit/runsvdir/current
	done
	}
installed_packages(){
	(
	pacman -Qn
	pacman -Qm
	) | sed -e's/ .*$//' | sort | uniq
	}
